### ISSUE TITLE
Can't find matches in China

### ISSUE THREAD

**Issue by pengowray** [Hambergo/9kmmrbot#23]
In case you guys don't know, the bot fails to find matches when they're in China / Perfect World. 

The commands `!np`, `!gm` and `!lg` say "Game wasn't found"

**Comment by Hambergo** [comment]
It's a known problem, I'm not sure if it's possible to fix without having another client open for China / PW servers, also I don't know how to make the client login to the China / PW servers instead of normal steam servers, so it's probably not going to be added
