### ISSUE TITLE
Steam  Cannot read property 'host' of undefined

### ISSUE THREAD

**Issue by Banonevar** [Hambergo/9kmmrbot#26]
It's issue more related to `steam` library, but maybe you have same problem and know way to fix? 
```
\9kmmrbot-master\node_modules\steam\lib\steam_client.js:47
  this.emit('debug', 'connecting to ' + server.host + ':' + server.port);
                                               ^

TypeError: Cannot read property 'host' of undefined
```

**Comment by Hambergo** [comment]
npm install should resolve this i believe,
but you can save this [servers.json](https://api.steampowered.com/ISteamDirectory/GetCMList/v1/?cellid=0)
to servers.json in the steam directory and it should work

**Comment by Banonevar** [comment]
I have that file here
![img](https://i.imgur.com/CuANxfh.png)

**Comment by Hambergo** [comment]
in that case, try adding the following to the collection "servers" in your database, it should overwrite the default server list:
`[
        {
                "host" : "162.254.197.180",
                "port" : 27017
        },
        {
                "host" : "162.254.196.84",
                "port" : 27017
        },
        {
                "host" : "162.254.197.42",
                "port" : 27017
        },
        {
                "host" : "162.254.197.42",
                "port" : 27018
        },
        {
                "host" : "162.254.197.180",
                "port" : 27018
        },
        {
                "host" : "162.254.197.181",
                "port" : 27018
        },
        {
                "host" : "162.254.196.84",
                "port" : 27018
        },
        {
                "host" : "162.254.196.67",
                "port" : 27017
        },
        {
                "host" : "162.254.196.68",
                "port" : 27018
        },
        {
                "host" : "162.254.196.68",
                "port" : 27017
        },
        {
                "host" : "162.254.197.181",
                "port" : 27017
        },
        {
                "host" : "162.254.197.40",
                "port" : 27017
        },
        {
                "host" : "162.254.197.181",
                "port" : 27019
        },
        {
                "host" : "162.254.197.40",
                "port" : 27019
        },
        {
                "host" : "162.254.197.180",
                "port" : 27019
        },
        {
                "host" : "162.254.197.42",
                "port" : 27019
        },
        {
                "host" : "162.254.196.67",
                "port" : 27019
        },
        {
                "host" : "162.254.196.83",
                "port" : 27018
        },
        {
                "host" : "162.254.196.83",
                "port" : 27019
        },
        {
                "host" : "162.254.196.84",
                "port" : 27019
        },
        {
                "host" : "162.254.196.68",
                "port" : 27019
        },
        {
                "host" : "162.254.196.83",
                "port" : 27017
        },
        {
                "host" : "162.254.196.67",
                "port" : 27018
        },
        {
                "host" : "162.254.197.40",
                "port" : 27018
        },
        {
                "host" : "146.66.152.10",
                "port" : 27018
        },
        {
                "host" : "146.66.152.10",
                "port" : 27017
        },
        {
                "host" : "146.66.152.10",
                "port" : 27019
        },
        {
                "host" : "155.133.242.9",
                "port" : 27017
        },
        {
                "host" : "155.133.242.8",
                "port" : 27017
        },
        {
                "host" : "155.133.242.8",
                "port" : 27019
        },
        {
                "host" : "155.133.242.9",
                "port" : 27019
        },
        {
                "host" : "146.66.152.11",
                "port" : 27017
        },
        {
                "host" : "146.66.152.11",
                "port" : 27018
        },
        {
                "host" : "185.25.180.14",
                "port" : 27018
        },
        {
                "host" : "155.133.242.8",
                "port" : 27018
        },
        {
                "host" : "185.25.180.15",
                "port" : 27018
        },
        {
                "host" : "155.133.242.9",
                "port" : 27018
        },
        {
                "host" : "185.25.180.14",
                "port" : 27019
        },
        {
                "host" : "185.25.180.14",
                "port" : 27017
        },
        {
                "host" : "185.25.180.15",
                "port" : 27017
        },
        {
                "host" : "185.25.180.15",
                "port" : 27019
        },
        {
                "host" : "146.66.152.11",
                "port" : 27019
        },
        {
                "host" : "155.133.248.50",
                "port" : 27017
        },
        {
                "host" : "155.133.248.52",
                "port" : 27017
        },
        {
                "host" : "155.133.248.52",
                "port" : 27019
        },
        {
                "host" : "155.133.248.50",
                "port" : 27018
        },
        {
                "host" : "155.133.248.53",
                "port" : 27018
        },
        {
                "host" : "155.133.248.53",
                "port" : 27017
        },
        {
                "host" : "155.133.248.53",
                "port" : 27019
        },
        {
                "host" : "155.133.248.51",
                "port" : 27017
        },
        {
                "host" : "155.133.248.51",
                "port" : 27019
        },
        {
                "host" : "155.133.248.52",
                "port" : 27018
        },
        {
                "host" : "155.133.248.50",
                "port" : 27019
        },
        {
                "host" : "155.133.248.51",
                "port" : 27018
        },
        {
                "host" : "155.133.229.250",
                "port" : 27017
        },
        {
                "host" : "155.133.246.69",
                "port" : 27017
        },
        {
                "host" : "155.133.246.69",
                "port" : 27018
        },
        {
                "host" : "155.133.246.68",
                "port" : 27019
        },
        {
                "host" : "155.133.246.69",
                "port" : 27019
        },
        {
                "host" : "155.133.229.250",
                "port" : 27018
        },
        {
                "host" : "155.133.229.251",
                "port" : 27018
        },
        {
                "host" : "155.133.229.250",
                "port" : 27019
        },
        {
                "host" : "155.133.229.251",
                "port" : 27019
        },
        {
                "host" : "155.133.229.251",
                "port" : 27017
        },
        {
                "host" : "155.133.246.68",
                "port" : 27017
        },
        {
                "host" : "155.133.246.68",
                "port" : 27018
        },
        {
                "host" : "162.254.192.101",
                "port" : 27018
        },
        {
                "host" : "162.254.192.100",
                "port" : 27019
        },
        {
                "host" : "162.254.192.101",
                "port" : 27019
        },
        {
                "host" : "162.254.192.109",
                "port" : 27017
        },
        {
                "host" : "162.254.192.109",
                "port" : 27018
        },
        {
                "host" : "162.254.192.100",
                "port" : 27017
        },
        {
                "host" : "162.254.192.108",
                "port" : 27019
        },
        {
                "host" : "162.254.192.108",
                "port" : 27018
        },
        {
                "host" : "162.254.192.109",
                "port" : 27019
        },
        {
                "host" : "162.254.192.100",
                "port" : 27018
        },
        {
                "host" : "162.254.192.101",
                "port" : 27017
        },
        {
                "host" : "162.254.192.108",
                "port" : 27017
        },
        {
                "host" : "155.133.230.50",
                "port" : 27019
        },
        {
                "host" : "155.133.230.50",
                "port" : 27018
        }
]`

**Comment by Banonevar** [comment]
Thx! it helped
