### ISSUE TITLE
Missed collections

### ISSUE THREAD

**Issue by Banonevar** [Hambergo/9kmmrbot#27]
I thimk you miss create collections like `game modes`, `heroes`, `notable players`, e.t.c

**Comment by Banonevar** [comment]
So because of that bot not show medal names, heroes names, and other stuff broken

**Comment by Hambergo** [comment]
medals collection:
`[
        {
                "rank_tier" : 0,
                "name" : "Uncalibrated"
        },
        {
                "rank_tier" : 11,
                "name" : "Herald☆1"
        },
        {
                "rank_tier" : 12,
                "name" : "Herald☆2"
        },
        {
                "rank_tier" : 13,
                "name" : "Herald☆3"
        },
        {
                "rank_tier" : 14,
                "name" : "Herald☆4"
        },
        {
                "rank_tier" : 15,
                "name" : "Herald☆5"
        },
        {
                "rank_tier" : 21,
                "name" : "Guardian☆1"
        },
        {
                "rank_tier" : 22,
                "name" : "Guardian☆2"
        },
        {
                "rank_tier" : 23,
                "name" : "Guardian☆3"
        },
        {
                "rank_tier" : 24,
                "name" : "Guardian☆4"
        },
        {
                "rank_tier" : 25,
                "name" : "Guardian☆5"
        },
        {
                "rank_tier" : 31,
                "name" : "Crusader☆1"
        },
        {
                "rank_tier" : 32,
                "name" : "Crusader☆2"
        },
        {
                "rank_tier" : 33,
                "name" : "Crusader☆3"
        },
        {
                "rank_tier" : 34,
                "name" : "Crusader☆4"
        },
        {
                "rank_tier" : 35,
                "name" : "Crusader☆5"
        },
        {
                "rank_tier" : 41,
                "name" : "Archon☆1"
        },
        {
                "rank_tier" : 42,
                "name" : "Archon☆2"
        },
        {
                "rank_tier" : 43,
                "name" : "Archon☆3"
        },
        {
                "rank_tier" : 44,
                "name" : "Archon☆4"
        },
        {
                "rank_tier" : 45,
                "name" : "Archon☆5"
        },
        {
                "rank_tier" : 51,
                "name" : "Legend☆1"
        },
        {
                "rank_tier" : 52,
                "name" : "Legend☆2"
        },
        {
                "rank_tier" : 53,
                "name" : "Legend☆3"
        },
        {
                "rank_tier" : 54,
                "name" : "Legend☆4"
        },
        {
                "rank_tier" : 55,
                "name" : "Legend☆5"
        },
        {
                "rank_tier" : 61,
                "name" : "Ancient☆1"
        },
        {
                "rank_tier" : 62,
                "name" : "Ancient☆2"
        },
        {
                "rank_tier" : 63,
                "name" : "Ancient☆3"
        },
        {
                "rank_tier" : 64,
                "name" : "Ancient☆4"
        },
        {
                "rank_tier" : 65,
                "name" : "Ancient☆5"
        },
        {
                "rank_tier" : 71,
                "name" : "Divine☆1"
        },
        {
                "rank_tier" : 72,
                "name" : "Divine☆2"
        },
        {
                "rank_tier" : 73,
                "name" : "Divine☆3"
        },
        {
                "rank_tier" : 74,
                "name" : "Divine☆4"
        },
        {
                "rank_tier" : 75,
                "name" : "Divine☆5"
        },
        {
                "rank_tier" : 80,
                "name" : "Immortal"
        },
        {
                "rank_tier" : 46,
                "name" : "Archon☆6"
        },
        {
                "rank_tier" : 47,
                "name" : "Archon☆7"
        },
        {
                "rank_tier" : 36,
                "name" : "Crusader☆6"
        },
        {
                "rank_tier" : 37,
                "name" : "Crusader☆7"
        },
        {
                "rank_tier" : 16,
                "name" : "Herald☆6"
        },
        {
                "rank_tier" : 17,
                "name" : "Herald☆7"
        },
        {
                "rank_tier" : 26,
                "name" : "Guardian☆6"
        },
        {
                "rank_tier" : 27,
                "name" : "Guardian☆7"
        },
        {
                "rank_tier" : 76,
                "name" : "Divine☆6"
        },
        {
                "rank_tier" : 77,
                "name" : "Divine☆7"
        },
        {
                "rank_tier" : 56,
                "name" : "Legend☆6"
        },
        {
                "rank_tier" : 57,
                "name" : "Legend☆7"
        },
        {
                "rank_tier" : 66,
                "name" : "Ancient☆6"
        },
        {
                "rank_tier" : 67,
                "name" : "Ancient☆7"
        }
]`
game modes collection:
`[
        {
                "id" : "1",
                "name" : "All Pick"
        },
        {
                "id" : "2",
                "name" : "Captains Mode"
        },
        {
                "id" : "3",
                "name" : "Random Draft"
        },
        {
                "id" : "4",
                "name" : "Single Draft"
        },
        {
                "id" : "5",
                "name" : "All Random"
        },
        {
                "id" : "6",
                "name" : "Intro"
        },
        {
                "id" : "7",
                "name" : "Diretide"
        },
        {
                "id" : "8",
                "name" : "Reverse Captains Mode"
        },
        {
                "id" : "9",
                "name" : "The Greeviling"
        },
        {
                "id" : "10",
                "name" : "Tutorial"
        },
        {
                "id" : "11",
                "name" : "Mid Only"
        },
        {
                "id" : "12",
                "name" : "Least Played"
        },
        {
                "id" : "13",
                "name" : "New Player Pool"
        },
        {
                "id" : "14",
                "name" : "Compendium Matchmaking"
        },
        {
                "id" : "15",
                "name" : "Custom Game"
        },
        {
                "id" : "16",
                "name" : "Captains Draft"
        },
        {
                "id" : "18",
                "name" : "Ability Draft"
        },
        {
                "id" : "19",
                "name" : "Event Game"
        },
        {
                "id" : "20",
                "name" : "All Random Deathmatch"
        },
        {
                "id" : "21",
                "name" : "1v1 Mid Only"
        },
        {
                "id" : "22",
                "name" : "All Pick"
        },
        {
                "id" : "23",
                "name" : "TURBO"
        },
        {
                "id" : "24",
                "name" : "Mutation"
        }
]`
heroes collection:
`[
        {
                "localized_name" : "Not Picked",
                "id" : "0",
                "custom" : false
        },
        {
                "localized_name" : "Anti-Mage",
                "name" : "npc_dota_hero_antimage",
                "id" : "1",
                "custom" : false
        },
        {
                "localized_name" : "Axe",
                "name" : "npc_dota_hero_axe",
                "id" : "2",
                "custom" : false
        },
        {
                "localized_name" : "Bane",
                "name" : "npc_dota_hero_bane",
                "id" : "3",
                "custom" : false
        },
        {
                "localized_name" : "Bloodseeker",
                "name" : "npc_dota_hero_bloodseeker",
                "id" : "4",
                "custom" : false
        },
        {
                "localized_name" : "Crystal Maiden",
                "name" : "npc_dota_hero_crystal_maiden",
                "id" : "5",
                "custom" : false
        },
        {
                "localized_name" : "Drow Ranger",
                "name" : "npc_dota_hero_drow_ranger",
                "id" : "6",
                "custom" : false
        },
        {
                "localized_name" : "Earthshaker",
                "name" : "npc_dota_hero_earthshaker",
                "id" : "7",
                "custom" : false
        },
        {
                "localized_name" : "Juggernaut",
                "name" : "npc_dota_hero_juggernaut",
                "id" : "8",
                "custom" : false
        },
        {
                "localized_name" : "Mirana",
                "name" : "npc_dota_hero_mirana",
                "id" : "9",
                "custom" : false
        },
        {
                "localized_name" : "Morphling",
                "name" : "npc_dota_hero_morphling",
                "id" : "10",
                "custom" : false
        },
        {
                "localized_name" : "Shadow Fiend",
                "name" : "npc_dota_hero_nevermore",
                "id" : "11",
                "custom" : false
        },
        {
                "localized_name" : "Phantom Lancer",
                "name" : "npc_dota_hero_phantom_lancer",
                "id" : "12",
                "custom" : false
        },
        {
                "localized_name" : "Puck",
                "name" : "npc_dota_hero_puck",
                "id" : "13",
                "custom" : false
        },
        {
                "localized_name" : "Pudge",
                "name" : "npc_dota_hero_pudge",
                "id" : "14",
                "custom" : false
        },
        {
                "localized_name" : "Razor",
                "name" : "npc_dota_hero_razor",
                "id" : "15",
                "custom" : false
        },
        {
                "localized_name" : "Sand King",
                "name" : "npc_dota_hero_sand_king",
                "id" : "16",
                "custom" : false
        },
        {
                "localized_name" : "Storm Spirit",
                "name" : "npc_dota_hero_storm_spirit",
                "id" : "17",
                "custom" : false
        },
        {
                "localized_name" : "Sven",
                "name" : "npc_dota_hero_sven",
                "id" : "18",
                "custom" : false
        },
        {
                "localized_name" : "Tiny",
                "name" : "npc_dota_hero_tiny",
                "id" : "19",
                "custom" : false
        },
        {
                "localized_name" : "Vengeful Spirit",
                "name" : "npc_dota_hero_vengefulspirit",
                "id" : "20",
                "custom" : false
        },
        {
                "localized_name" : "Windranger",
                "name" : "npc_dota_hero_windrunner",
                "id" : "21",
                "custom" : false
        },
        {
                "localized_name" : "Zeus",
                "name" : "npc_dota_hero_zuus",
                "id" : "22",
                "custom" : false
        },
        {
                "localized_name" : "Kunkka",
                "name" : "npc_dota_hero_kunkka",
                "id" : "23",
                "custom" : false
        },
        {
                "localized_name" : "Lina",
                "name" : "npc_dota_hero_lina",
                "id" : "25",
                "custom" : false
        },
        {
                "localized_name" : "Lion",
                "name" : "npc_dota_hero_lion",
                "id" : "26",
                "custom" : false
        },
        {
                "localized_name" : "Shadow Shaman",
                "name" : "npc_dota_hero_shadow_shaman",
                "id" : "27",
                "custom" : false
        },
        {
                "localized_name" : "Slardar",
                "name" : "npc_dota_hero_slardar",
                "id" : "28",
                "custom" : false
        },
        {
                "localized_name" : "Tidehunter",
                "name" : "npc_dota_hero_tidehunter",
                "id" : "29",
                "custom" : false
        },
        {
                "localized_name" : "Witch Doctor",
                "name" : "npc_dota_hero_witch_doctor",
                "id" : "30",
                "custom" : false
        },
        {
                "localized_name" : "Lich",
                "name" : "npc_dota_hero_lich",
                "id" : "31",
                "custom" : false
        },
        {
                "localized_name" : "Riki",
                "name" : "npc_dota_hero_riki",
                "id" : "32",
                "custom" : false
        },
        {
                "localized_name" : "Enigma",
                "name" : "npc_dota_hero_enigma",
                "id" : "33",
                "custom" : false
        },
        {
                "localized_name" : "Tinker",
                "name" : "npc_dota_hero_tinker",
                "id" : "34",
                "custom" : false
        },
        {
                "localized_name" : "Sniper",
                "name" : "npc_dota_hero_sniper",
                "id" : "35",
                "custom" : false
        },
        {
                "localized_name" : "Necrophos",
                "name" : "npc_dota_hero_necrolyte",
                "id" : "36",
                "custom" : false
        },
        {
                "localized_name" : "Warlock",
                "name" : "npc_dota_hero_warlock",
                "id" : "37",
                "custom" : false
        },
        {
                "localized_name" : "Beastmaster",
                "name" : "npc_dota_hero_beastmaster",
                "id" : "38",
                "custom" : false
        },
        {
                "localized_name" : "Queen of Pain",
                "name" : "npc_dota_hero_queenofpain",
                "id" : "39",
                "custom" : false
        },
        {
                "localized_name" : "Venomancer",
                "name" : "npc_dota_hero_venomancer",
                "id" : "40",
                "custom" : false
        },
        {
                "localized_name" : "Faceless Void",
                "name" : "npc_dota_hero_faceless_void",
                "id" : "41",
                "custom" : false
        },
        {
                "localized_name" : "Wraith King",
                "name" : "npc_dota_hero_skeleton_king",
                "id" : "42",
                "custom" : false
        },
        {
                "localized_name" : "Death Prophet",
                "name" : "npc_dota_hero_death_prophet",
                "id" : "43",
                "custom" : false
        },
        {
                "localized_name" : "Phantom Assassin",
                "name" : "npc_dota_hero_phantom_assassin",
                "id" : "44",
                "custom" : false
        },
        {
                "localized_name" : "Pugna",
                "name" : "npc_dota_hero_pugna",
                "id" : "45",
                "custom" : false
        },
        {
                "localized_name" : "Templar Assassin",
                "name" : "npc_dota_hero_templar_assassin",
                "id" : "46",
                "custom" : false
        },
        {
                "localized_name" : "Viper",
                "name" : "npc_dota_hero_viper",
                "id" : "47",
                "custom" : false
        },
        {
                "localized_name" : "Luna",
                "name" : "npc_dota_hero_luna",
                "id" : "48",
                "custom" : false
        },
        {
                "localized_name" : "Dragon Knight",
                "name" : "npc_dota_hero_dragon_knight",
                "id" : "49",
                "custom" : false
        },
        {
                "localized_name" : "Dazzle",
                "name" : "npc_dota_hero_dazzle",
                "id" : "50",
                "custom" : false
        },
        {
                "localized_name" : "Clockwerk",
                "name" : "npc_dota_hero_rattletrap",
                "id" : "51",
                "custom" : false
        },
        {
                "localized_name" : "Leshrac",
                "name" : "npc_dota_hero_leshrac",
                "id" : "52",
                "custom" : false
        },
        {
                "localized_name" : "Nature's Prophet",
                "name" : "npc_dota_hero_furion",
                "id" : "53",
                "custom" : false
        },
        {
                "localized_name" : "Lifestealer",
                "name" : "npc_dota_hero_life_stealer",
                "id" : "54",
                "custom" : false
        },
        {
                "localized_name" : "Dark Seer",
                "name" : "npc_dota_hero_dark_seer",
                "id" : "55",
                "custom" : false
        },
        {
                "localized_name" : "Clinkz",
                "name" : "npc_dota_hero_clinkz",
                "id" : "56",
                "custom" : false
        },
        {
                "localized_name" : "Omniknight",
                "name" : "npc_dota_hero_omniknight",
                "id" : "57",
                "custom" : false
        },
        {
                "localized_name" : "Enchantress",
                "name" : "npc_dota_hero_enchantress",
                "id" : "58",
                "custom" : false
        },
        {
                "localized_name" : "Huskar",
                "name" : "npc_dota_hero_huskar",
                "id" : "59",
                "custom" : false
        },
        {
                "localized_name" : "Night Stalker",
                "name" : "npc_dota_hero_night_stalker",
                "id" : "60",
                "custom" : false
        },
        {
                "localized_name" : "Broodmother",
                "name" : "npc_dota_hero_broodmother",
                "id" : "61",
                "custom" : false
        },
        {
                "localized_name" : "Bounty Hunter",
                "name" : "npc_dota_hero_bounty_hunter",
                "id" : "62",
                "custom" : false
        },
        {
                "localized_name" : "Weaver",
                "name" : "npc_dota_hero_weaver",
                "id" : "63",
                "custom" : false
        },
        {
                "localized_name" : "Jakiro",
                "name" : "npc_dota_hero_jakiro",
                "id" : "64",
                "custom" : false
        },
        {
                "localized_name" : "Batrider",
                "name" : "npc_dota_hero_batrider",
                "id" : "65",
                "custom" : false
        },
        {
                "localized_name" : "Chen",
                "name" : "npc_dota_hero_chen",
                "id" : "66",
                "custom" : false
        },
        {
                "localized_name" : "Spectre",
                "name" : "npc_dota_hero_spectre",
                "id" : "67",
                "custom" : false
        },
        {
                "localized_name" : "Ancient Apparition",
                "name" : "npc_dota_hero_ancient_apparition",
                "id" : "68",
                "custom" : false
        },
        {
                "localized_name" : "Doom",
                "name" : "npc_dota_hero_doom_bringer",
                "id" : "69",
                "custom" : false
        },
        {
                "localized_name" : "Ursa",
                "name" : "npc_dota_hero_ursa",
                "id" : "70",
                "custom" : false
        },
        {
                "localized_name" : "Spirit Breaker",
                "name" : "npc_dota_hero_spirit_breaker",
                "id" : "71",
                "custom" : false
        },
        {
                "localized_name" : "Gyrocopter",
                "name" : "npc_dota_hero_gyrocopter",
                "id" : "72",
                "custom" : false
        },
        {
                "localized_name" : "Alchemist",
                "name" : "npc_dota_hero_alchemist",
                "id" : "73",
                "custom" : false
        },
        {
                "localized_name" : "Invoker",
                "name" : "npc_dota_hero_invoker",
                "id" : "74",
                "custom" : false
        },
        {
                "localized_name" : "Silencer",
                "name" : "npc_dota_hero_silencer",
                "id" : "75",
                "custom" : false
        },
        {
                "localized_name" : "Outworld Devourer",
                "name" : "npc_dota_hero_obsidian_destroyer",
                "id" : "76",
                "custom" : false
        },
        {
                "localized_name" : "Lycan",
                "name" : "npc_dota_hero_lycan",
                "id" : "77",
                "custom" : false
        },
        {
                "localized_name" : "Brewmaster",
                "name" : "npc_dota_hero_brewmaster",
                "id" : "78",
                "custom" : false
        },
        {
                "localized_name" : "Shadow Demon",
                "name" : "npc_dota_hero_shadow_demon",
                "id" : "79",
                "custom" : false
        },
        {
                "localized_name" : "Lone Druid",
                "name" : "npc_dota_hero_lone_druid",
                "id" : "80",
                "custom" : false
        },
        {
                "localized_name" : "Chaos Knight",
                "name" : "npc_dota_hero_chaos_knight",
                "id" : "81",
                "custom" : false
        },
        {
                "localized_name" : "Meepo",
                "name" : "npc_dota_hero_meepo",
                "id" : "82",
                "custom" : false
        },
        {
                "localized_name" : "Treant Protector",
                "name" : "npc_dota_hero_treant",
                "id" : "83",
                "custom" : false
        },
        {
                "localized_name" : "Ogre Magi",
                "name" : "npc_dota_hero_ogre_magi",
                "id" : "84",
                "custom" : false
        },
        {
                "localized_name" : "Undying",
                "name" : "npc_dota_hero_undying",
                "id" : "85",
                "custom" : false
        },
        {
                "localized_name" : "Rubick",
                "name" : "npc_dota_hero_rubick",
                "id" : "86",
                "custom" : false
        },
        {
                "localized_name" : "Disruptor",
                "name" : "npc_dota_hero_disruptor",
                "id" : "87",
                "custom" : false
        },
        {
                "localized_name" : "Nyx Assassin",
                "name" : "npc_dota_hero_nyx_assassin",
                "id" : "88",
                "custom" : false
        },
        {
                "localized_name" : "Naga Siren",
                "name" : "npc_dota_hero_naga_siren",
                "id" : "89",
                "custom" : false
        },
        {
                "localized_name" : "Keeper of the Light",
                "name" : "npc_dota_hero_keeper_of_the_light",
                "id" : "90",
                "custom" : false
        },
        {
                "localized_name" : "Io",
                "name" : "npc_dota_hero_wisp",
                "id" : "91",
                "custom" : false
        },
        {
                "localized_name" : "Visage",
                "name" : "npc_dota_hero_visage",
                "id" : "92",
                "custom" : false
        },
        {
                "localized_name" : "Slark",
                "name" : "npc_dota_hero_slark",
                "id" : "93",
                "custom" : false
        },
        {
                "localized_name" : "Medusa",
                "name" : "npc_dota_hero_medusa",
                "id" : "94",
                "custom" : false
        },
        {
                "localized_name" : "Troll Warlord",
                "name" : "npc_dota_hero_troll_warlord",
                "id" : "95",
                "custom" : false
        },
        {
                "localized_name" : "Centaur Warrunner",
                "name" : "npc_dota_hero_centaur",
                "id" : "96",
                "custom" : false
        },
        {
                "localized_name" : "Magnus",
                "name" : "npc_dota_hero_magnataur",
                "id" : "97",
                "custom" : false
        },
        {
                "localized_name" : "Timbersaw",
                "name" : "npc_dota_hero_shredder",
                "id" : "98",
                "custom" : false
        },
        {
                "localized_name" : "Bristleback",
                "name" : "npc_dota_hero_bristleback",
                "id" : "99",
                "custom" : false
        },
        {
                "localized_name" : "Tusk",
                "name" : "npc_dota_hero_tusk",
                "id" : "100",
                "custom" : false
        },
        {
                "localized_name" : "Skywrath Mage",
                "name" : "npc_dota_hero_skywrath_mage",
                "id" : "101",
                "custom" : false
        },
        {
                "localized_name" : "Abaddon",
                "name" : "npc_dota_hero_abaddon",
                "id" : "102",
                "custom" : false
        },
        {
                "localized_name" : "Elder Titan",
                "name" : "npc_dota_hero_elder_titan",
                "id" : "103",
                "custom" : false
        },
        {
                "localized_name" : "Legion Commander",
                "name" : "npc_dota_hero_legion_commander",
                "id" : "104",
                "custom" : false
        },
        {
                "localized_name" : "Techies",
                "name" : "npc_dota_hero_techies",
                "id" : "105",
                "custom" : false
        },
        {
                "localized_name" : "Ember Spirit",
                "name" : "npc_dota_hero_ember_spirit",
                "id" : "106",
                "custom" : false
        },
        {
                "localized_name" : "Earth Spirit",
                "name" : "npc_dota_hero_earth_spirit",
                "id" : "107",
                "custom" : false
        },
        {
                "localized_name" : "Underlord",
                "name" : "npc_dota_hero_abyssal_underlord",
                "id" : "108",
                "custom" : false
        },
        {
                "localized_name" : "Terrorblade",
                "name" : "npc_dota_hero_terrorblade",
                "id" : "109",
                "custom" : false
        },
        {
                "localized_name" : "Phoenix",
                "name" : "npc_dota_hero_phoenix",
                "id" : "110",
                "custom" : false
        },
        {
                "localized_name" : "Oracle",
                "name" : "npc_dota_hero_oracle",
                "id" : "111",
                "custom" : false
        },
        {
                "localized_name" : "Winter Wyvern",
                "name" : "npc_dota_hero_winter_wyvern",
                "id" : "112",
                "custom" : false
        },
        {
                "localized_name" : "Arc Warden",
                "name" : "npc_dota_hero_arc_warden",
                "id" : "113",
                "custom" : false
        },
        {
                "localized_name" : "Monkey King",
                "name" : "npc_dota_hero_monkey_king",
                "id" : "114",
                "custom" : false
        },
        {
                "localized_name" : "Dark Willow",
                "name" : "npc_dota_hero_dark_willow",
                "id" : "119",
                "custom" : false
        },
        {
                "localized_name" : "Pangolier",
                "name" : "npc_dota_hero_pangolier",
                "id" : "120",
                "custom" : false
        },
        {
                "localized_name" : "Grimstroke",
                "name" : "npc_dota_hero_grimstroke",
                "id" : "121",
                "custom" : false
        },
        {
                "localized_name" : "Mars",
                "name" : "npc_dota_hero_mars",
                "id" : "129",
                "custom" : false
        }
]`

**Comment by Banonevar** [comment]
Is that all? I mean maybe some others collection is missed.
Cool if i can get missed

**Comment by Hambergo** [comment]
I think that's all, the rest aren't needed to have initial data in.
There's no need to send the notable players collection because you can fill it yourself with !9kmmrbot addnp or !9kmmrbot addglobalnp

**Comment by Banonevar** [comment]
Big thx 👍
