### ISSUE TITLE
New command for globalmod !9kmmrbot addacc id channel

### ISSUE THREAD

**Issue by Banonevar** [Hambergo/9kmmrbot#31]
I suggest add new command, for adding some steam accounts to some twitch channel
Example of usage: `!9kmmrbot addacc id channel`
But you can do format you wan't

**Comment by tverghis** [comment]
Could you give an example of why you might want to use this command? Is it just for testing purposes so you don't have to write the `addacc` command in the streamer's channel? Or some other use case? 

Also, were you thinking this command would only be available to the 9kmmrbot Global Mods, or any 9kmmrbot mod?

Thanks!

**Comment by Banonevar** [comment]
I've already done it in my fork, so.. 

Yea, it's just testing purposes.
