### ISSUE TITLE
Inconsistencies with channel settings

### ISSUE THREAD

**Issue by tverghis** [Hambergo/9kmmrbot#36]
Eg: A channel's delay is set on the `settings` document, but it's cooldown is stored on the `channel` itself. These kinds of settings should probably exist directly on the `channel`, but we should be consistent, one way or the other.

**Comment by Hambergo** [comment]
Yeah, I think that the collection `settings` is unnecessary now.
Can add all of the documents in `settings` to a document in `channels`
`Include Self Channel`, `emotes Channel`, `Global Mod`, `Delayed Channel`
