### ISSUE TITLE
Command to get streamer's current hero (viewer command)

### ISSUE THREAD

**Issue by kektobiologist** [Hambergo/9kmmrbot#52]
Hi
I'd like to know if it's possible for a viewer to get the current hero played by the streamer. It can be used by another bot to search through all dota streamers and find one playing a particular hero (like it's done in the dota client to search for a particular hero game). Helpful for learning a hero. This is more of a feature request really :)
EDIT: I'd be happy to make a PR if this is something you're okay with

**Comment by Hambergo** [comment]
I didn't really understand what it is for
I don't think it's needed for viewers to use the command if they're on the stream, and if it's for other bots, i don't think that i want the integration between them a command that'll show in chat

**Comment by kektobiologist** [comment]
Right, I intended this for other bots only. It's like a way to find all streamers playing a particular hero. You can close the issue if it's not interesting
