### ISSUE TITLE
Auto create predictions

### ISSUE THREAD

**Issue by Bakabot307** [Hambergo/9kmmrbot#61]
It would be nice if the bot can open and close predictions automatically

**Comment by Hambergo** [comment]
I'm afraid it's not really possible
twitch did add prediction apis, but it requires a token of the broadcaster with certain scope, which isn't something that can be done currently
will need to get a token of each streamer that want it - so need to figure out how to send it
and also - figuring out game start/game end is really unreliable, and on top of it checking match result would be an issue

**Comment by Geczy** [comment]
https://dotabod.com possible with this now
