### ISSUE TITLE
Bot no longer recognises channel

### ISSUE THREAD

**Issue by kilroy98** [Hambergo/9kmmrbot#67]
I am a moderator on the .tv/lia_more channel and the bot has not seen the matches that were played on the stream for a long time. At the same time, he sees the rank of the account.
The bot was re-added to the channel, I tried to add a Steam account to the bot for different types of SteamID and this did not help, unfortunately.

@Hambergo

**Comment by Hambergo** [comment]
hey @kilroy98 , sorry!

Sadly recently enough, steam decided to respect user's privacy settings and not show what game they are playing through the friends list if they have it private/friends only.

If possible, change the privacy settings of the account to public game data,
if not, can add "hambergosmurf2" on steam and let me know

**Comment by kilroy98** [comment]
Sorry for such a long answer. Yes, indeed changing the Steam privacy settings helped solve the problem. I think you need to write here and in the description of the bot on Twitch in capital letters that now you need to change the account privacy settings so that the bot functions normally
